// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2fOQeYrCGbX2S7BikMu5u_lLsMPHn1G4',
    appId: '1:587203270441:ios:7b06400c86644d96dfc938',
    messagingSenderId: '587203270441',
    projectId: 'appcomputadores-4ff1f',
    databaseURL: 'https://appcomputadores-4ff1f-default-rtdb.firebaseio.com',
    storageBucket: 'appcomputadores-4ff1f.firebasestorage.app',
    iosBundleId: 'com.example.appComputadores',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2fOQeYrCGbX2S7BikMu5u_lLsMPHn1G4',
    appId: '1:587203270441:ios:7b06400c86644d96dfc938',
    messagingSenderId: '587203270441',
    projectId: 'appcomputadores-4ff1f',
    databaseURL: 'https://appcomputadores-4ff1f-default-rtdb.firebaseio.com',
    storageBucket: 'appcomputadores-4ff1f.firebasestorage.app',
    iosBundleId: 'com.example.appComputadores',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgXE_zA5iL0dgVBmxGQK0ZEa6NU8hRf1U',
    appId: '1:587203270441:android:ee24f74e4ad82faadfc938',
    messagingSenderId: '587203270441',
    projectId: 'appcomputadores-4ff1f',
    databaseURL: 'https://appcomputadores-4ff1f-default-rtdb.firebaseio.com',
    storageBucket: 'appcomputadores-4ff1f.firebasestorage.app',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoRfXq9RfcMl6p7POcqCjBpYapac9mIf0',
    appId: '1:587203270441:web:a3d3e3a88f25047ddfc938',
    messagingSenderId: '587203270441',
    projectId: 'appcomputadores-4ff1f',
    authDomain: 'appcomputadores-4ff1f.firebaseapp.com',
    databaseURL: 'https://appcomputadores-4ff1f-default-rtdb.firebaseio.com',
    storageBucket: 'appcomputadores-4ff1f.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoRfXq9RfcMl6p7POcqCjBpYapac9mIf0',
    appId: '1:587203270441:web:a3d3e3a88f25047ddfc938',
    messagingSenderId: '587203270441',
    projectId: 'appcomputadores-4ff1f',
    authDomain: 'appcomputadores-4ff1f.firebaseapp.com',
    databaseURL: 'https://appcomputadores-4ff1f-default-rtdb.firebaseio.com',
    storageBucket: 'appcomputadores-4ff1f.firebasestorage.app',
  );
}
